# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/alpha.DESKTOP-1S1STEK/Documents/GitHub/ribGen/rib_gen_07_2UI.ui'
#
# Created: Wed Feb 08 09:19:53 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(403, 1072)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 391, 1051))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_B04 = QtGui.QLineEdit(self.tab)
        self.lineEdit_B04.setEnabled(True)
        self.lineEdit_B04.setGeometry(QtCore.QRect(110, 380, 70, 20))
        self.lineEdit_B04.setObjectName("lineEdit_B04")
        self.line_4 = QtGui.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(10, 630, 351, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(10, 220, 351, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_B03 = QtGui.QCheckBox(self.tab)
        self.checkBox_B03.setGeometry(QtCore.QRect(110, 410, 221, 16))
        self.checkBox_B03.setObjectName("checkBox_B03")
        self.checkBox_B01 = QtGui.QCheckBox(self.tab)
        self.checkBox_B01.setGeometry(QtCore.QRect(30, 240, 111, 16))
        self.checkBox_B01.setObjectName("checkBox_B01")
        self.horizontalSlider_2 = QtGui.QSlider(self.tab)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(190, 380, 161, 22))
        self.horizontalSlider_2.setMinimum(2)
        self.horizontalSlider_2.setMaximum(10)
        self.horizontalSlider_2.setProperty("value", 2)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(10, 430, 351, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lineEdit_A03 = QtGui.QLineEdit(self.tab)
        self.lineEdit_A03.setEnabled(True)
        self.lineEdit_A03.setGeometry(QtCore.QRect(230, 190, 91, 20))
        self.lineEdit_A03.setObjectName("lineEdit_A03")
        self.lineEdit_A02 = QtGui.QLineEdit(self.tab)
        self.lineEdit_A02.setEnabled(True)
        self.lineEdit_A02.setGeometry(QtCore.QRect(130, 190, 91, 20))
        self.lineEdit_A02.setObjectName("lineEdit_A02")
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(50, 190, 71, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalSlider = QtGui.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(190, 260, 161, 22))
        self.horizontalSlider.setMaximum(360)
        self.horizontalSlider.setProperty("value", 80)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.lineEdit_B02 = QtGui.QLineEdit(self.tab)
        self.lineEdit_B02.setEnabled(True)
        self.lineEdit_B02.setGeometry(QtCore.QRect(110, 290, 70, 20))
        self.lineEdit_B02.setObjectName("lineEdit_B02")
        self.checkBox_C01 = QtGui.QCheckBox(self.tab)
        self.checkBox_C01.setGeometry(QtCore.QRect(10, 650, 141, 21))
        self.checkBox_C01.setAutoExclusive(False)
        self.checkBox_C01.setObjectName("checkBox_C01")
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(10, 620, 131, 16))
        self.label_11.setObjectName("label_11")
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(10, 380, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(110, 320, 131, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(110, 350, 131, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.pushButton_01 = QtGui.QPushButton(self.tab)
        self.pushButton_01.setGeometry(QtCore.QRect(10, 450, 161, 31))
        self.pushButton_01.setObjectName("pushButton_01")
        self.lineEdit_B03 = QtGui.QLineEdit(self.tab)
        self.lineEdit_B03.setEnabled(True)
        self.lineEdit_B03.setGeometry(QtCore.QRect(200, 290, 70, 20))
        self.lineEdit_B03.setObjectName("lineEdit_B03")
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(9, 490, 131, 16))
        self.label_10.setObjectName("label_10")
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 100, 111, 41))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(130, 110, 231, 61))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_A01 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_A01.setAutoExclusive(True)
        self.checkBox_A01.setObjectName("checkBox_A01")
        self.verticalLayout.addWidget(self.checkBox_A01)
        self.checkBox_A02 = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_A02.setAutoExclusive(True)
        self.checkBox_A02.setObjectName("checkBox_A02")
        self.verticalLayout.addWidget(self.checkBox_A02)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(10, 210, 131, 16))
        self.label_8.setObjectName("label_8")
        self.checkBox_B02 = QtGui.QCheckBox(self.tab)
        self.checkBox_B02.setGeometry(QtCore.QRect(140, 240, 111, 16))
        self.checkBox_B02.setObjectName("checkBox_B02")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_9.setObjectName("label_9")
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 100, 351, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_B01 = QtGui.QLineEdit(self.tab)
        self.lineEdit_B01.setEnabled(True)
        self.lineEdit_B01.setGeometry(QtCore.QRect(110, 260, 70, 20))
        self.lineEdit_B01.setObjectName("lineEdit_B01")
        self.checkBox_C02 = QtGui.QCheckBox(self.tab)
        self.checkBox_C02.setEnabled(True)
        self.checkBox_C02.setGeometry(QtCore.QRect(140, 650, 211, 21))
        self.checkBox_C02.setAutoExclusive(False)
        self.checkBox_C02.setObjectName("checkBox_C02")
        self.lineEdit_c01 = QtGui.QLineEdit(self.tab)
        self.lineEdit_c01.setGeometry(QtCore.QRect(9, 510, 361, 101))
        self.lineEdit_c01.setObjectName("lineEdit_c01")
        self.label_23 = QtGui.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_A01 = QtGui.QLineEdit(self.tab)
        self.lineEdit_A01.setEnabled(True)
        self.lineEdit_A01.setGeometry(QtCore.QRect(130, 160, 91, 20))
        self.lineEdit_A01.setObjectName("lineEdit_A01")
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 690, 361, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_D01 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_D01.setEnabled(False)
        self.checkBox_D01.setAutoExclusive(True)
        self.checkBox_D01.setObjectName("checkBox_D01")
        self.horizontalLayout.addWidget(self.checkBox_D01)
        self.checkBox_D02 = QtGui.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_D02.setEnabled(False)
        self.checkBox_D02.setAutoExclusive(True)
        self.checkBox_D02.setObjectName("checkBox_D02")
        self.horizontalLayout.addWidget(self.checkBox_D02)
        self.toolButton_01 = QtGui.QToolButton(self.tab)
        self.toolButton_01.setGeometry(QtCore.QRect(340, 490, 31, 20))
        self.toolButton_01.setObjectName("toolButton_01")
        self.pushButton_02 = QtGui.QPushButton(self.tab)
        self.pushButton_02.setGeometry(QtCore.QRect(210, 450, 161, 31))
        self.pushButton_02.setObjectName("pushButton_02")
        self.pushButton_03 = QtGui.QPushButton(self.tab)
        self.pushButton_03.setGeometry(QtCore.QRect(10, 960, 161, 31))
        self.pushButton_03.setObjectName("pushButton_03")
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(300, 0, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 30, 341, 71))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 790, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(10, 730, 131, 16))
        self.label_13.setObjectName("label_13")
        self.line_6 = QtGui.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(10, 740, 351, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.checkBox_E01 = QtGui.QCheckBox(self.tab)
        self.checkBox_E01.setGeometry(QtCore.QRect(10, 760, 181, 16))
        self.checkBox_E01.setObjectName("checkBox_E01")
        self.lineEdit_D01 = QtGui.QLineEdit(self.tab)
        self.lineEdit_D01.setEnabled(True)
        self.lineEdit_D01.setGeometry(QtCore.QRect(70, 790, 41, 20))
        self.lineEdit_D01.setAccessibleName("")
        self.lineEdit_D01.setObjectName("lineEdit_D01")
        self.horizontalSlider_3 = QtGui.QSlider(self.tab)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(130, 790, 231, 22))
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setProperty("value", 50)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.checkBox_E03 = QtGui.QCheckBox(self.tab)
        self.checkBox_E03.setGeometry(QtCore.QRect(10, 820, 181, 16))
        self.checkBox_E03.setObjectName("checkBox_E03")
        self.lineEdit_D03 = QtGui.QLineEdit(self.tab)
        self.lineEdit_D03.setEnabled(True)
        self.lineEdit_D03.setGeometry(QtCore.QRect(110, 820, 41, 20))
        self.lineEdit_D03.setAccessibleName("")
        self.lineEdit_D03.setObjectName("lineEdit_D03")
        self.pushButton_04 = QtGui.QPushButton(self.tab)
        self.pushButton_04.setGeometry(QtCore.QRect(190, 960, 161, 31))
        self.pushButton_04.setObjectName("pushButton_04")
        self.pushButton_breakGPU = QtGui.QPushButton(self.tab)
        self.pushButton_breakGPU.setGeometry(QtCore.QRect(10, 850, 161, 31))
        self.pushButton_breakGPU.setObjectName("pushButton_breakGPU")
        self.pushButton_connectGPU = QtGui.QPushButton(self.tab)
        self.pushButton_connectGPU.setGeometry(QtCore.QRect(190, 850, 161, 31))
        self.pushButton_connectGPU.setObjectName("pushButton_connectGPU")
        self.line_8 = QtGui.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(10, 910, 351, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(10, 900, 131, 16))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_page2_A01 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A01.setGeometry(QtCore.QRect(40, 150, 291, 31))
        self.pushButton_page2_A01.setObjectName("pushButton_page2_A01")
        self.pushButton_page2_A02 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A02.setGeometry(QtCore.QRect(40, 240, 291, 31))
        self.pushButton_page2_A02.setObjectName("pushButton_page2_A02")
        self.pushButton_page2_A03 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A03.setGeometry(QtCore.QRect(40, 280, 291, 31))
        self.pushButton_page2_A03.setObjectName("pushButton_page2_A03")
        self.lineEdit_page2_A01 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_page2_A01.setGeometry(QtCore.QRect(180, 120, 41, 20))
        self.lineEdit_page2_A01.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_page2_A01.setObjectName("lineEdit_page2_A01")
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(40, 120, 141, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(40, 30, 141, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_page2_O01 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_page2_O01.setGeometry(QtCore.QRect(180, 30, 141, 20))
        self.lineEdit_page2_O01.setObjectName("lineEdit_page2_O01")
        self.pushButton_page2_O01 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_O01.setGeometry(QtCore.QRect(40, 60, 281, 25))
        self.pushButton_page2_O01.setObjectName("pushButton_page2_O01")
        self.llineEdit_page2_B01 = QtGui.QLineEdit(self.tab_2)
        self.llineEdit_page2_B01.setEnabled(False)
        self.llineEdit_page2_B01.setGeometry(QtCore.QRect(50, 650, 281, 41))
        self.llineEdit_page2_B01.setAlignment(QtCore.Qt.AlignCenter)
        self.llineEdit_page2_B01.setObjectName("llineEdit_page2_B01")
        self.pushButton_page2_B01 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_B01.setGeometry(QtCore.QRect(50, 620, 281, 25))
        self.pushButton_page2_B01.setObjectName("pushButton_page2_B01")
        self.pushButton_page2_B01_2 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_B01_2.setGeometry(QtCore.QRect(50, 700, 281, 25))
        self.pushButton_page2_B01_2.setObjectName("pushButton_page2_B01_2")
        self.line_5 = QtGui.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(20, 590, 371, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtGui.QFrame(self.tab_2)
        self.line_7.setGeometry(QtCore.QRect(10, 90, 371, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(60, 580, 331, 16))
        self.label_16.setObjectName("label_16")
        self.checkBox_page2_A01 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_page2_A01.setGeometry(QtCore.QRect(40, 210, 181, 19))
        self.checkBox_page2_A01.setObjectName("checkBox_page2_A01")
        self.pushButton_page2_A04 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A04.setGeometry(QtCore.QRect(40, 320, 291, 31))
        self.pushButton_page2_A04.setObjectName("pushButton_page2_A04")
        self.pushButton_page2_A05 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A05.setGeometry(QtCore.QRect(40, 360, 291, 31))
        self.pushButton_page2_A05.setObjectName("pushButton_page2_A05")
        self.checkBox_page2_A02 = QtGui.QCheckBox(self.tab_2)
        self.checkBox_page2_A02.setGeometry(QtCore.QRect(40, 410, 211, 19))
        self.checkBox_page2_A02.setObjectName("checkBox_page2_A02")
        self.pushButton_page2_A06 = QtGui.QPushButton(self.tab_2)
        self.pushButton_page2_A06.setGeometry(QtCore.QRect(40, 440, 291, 31))
        self.pushButton_page2_A06.setObjectName("pushButton_page2_A06")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "RIB Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Shutter Opening", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_B04.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Motion Blur Type", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_B03.setText(QtGui.QApplication.translate("MainWindow", "Ray traced Motion Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_B01.setText(QtGui.QApplication.translate("MainWindow", "Motion Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Shutter Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Start/End", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_C01.setText(QtGui.QApplication.translate("MainWindow", "UUID Rename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "RIB Archive Option", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Motion Samples", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Frame Open", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Frame Center", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Frame Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Shutter Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "Subframe", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_01.setText(QtGui.QApplication.translate("MainWindow", "Generate RIB Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Note:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Cache time range", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_A01.setText(QtGui.QApplication.translate("MainWindow", "Current Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_A02.setText(QtGui.QApplication.translate("MainWindow", "Start/End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "with Motion Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_B02.setText(QtGui.QApplication.translate("MainWindow", "Camera Blur", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Current Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_C02.setText(QtGui.QApplication.translate("MainWindow", "RIB  Sequences Only", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_c01.setText(QtGui.QApplication.translate("MainWindow", "type information before push \"Generate Rib Archive\"", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Curent Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_D01.setText(QtGui.QApplication.translate("MainWindow", "Delayed Read Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_D02.setText(QtGui.QApplication.translate("MainWindow", "Read Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton_01.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_02.setText(QtGui.QApplication.translate("MainWindow", "Generate Shave RIB", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_03.setText(QtGui.QApplication.translate("MainWindow", "Publish RIB Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Percentage", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "GPU Cache Option", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_E01.setText(QtGui.QApplication.translate("MainWindow", "reduce GPU cache Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_D01.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_E03.setText(QtGui.QApplication.translate("MainWindow", "GPU step", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_D03.setText(QtGui.QApplication.translate("MainWindow", "50", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_04.setText(QtGui.QApplication.translate("MainWindow", "Imput RIB Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_breakGPU.setText(QtGui.QApplication.translate("MainWindow", "Break GPUCache", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_connectGPU.setText(QtGui.QApplication.translate("MainWindow", "Connect GPUCache", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "RIB Operation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "RIB Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A01.setText(QtGui.QApplication.translate("MainWindow", "convert Hair Mesh to Curves", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A02.setText(QtGui.QApplication.translate("MainWindow", "Reverse  U", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A03.setText(QtGui.QApplication.translate("MainWindow", "Reverse V", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_page2_A01.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "hairs/pre Mesh:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Name Meshes Title:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_O01.setText(QtGui.QApplication.translate("MainWindow", "Rename Selected Poly Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.llineEdit_page2_B01.setText(QtGui.QApplication.translate("MainWindow", "Pxr Shader Select", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_B01.setText(QtGui.QApplication.translate("MainWindow", "Get PxrShader", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_B01_2.setText(QtGui.QApplication.translate("MainWindow", "Assign PxrShader to ShaveHair", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Assign Pixar Renderman Shader", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_page2_A01.setText(QtGui.QApplication.translate("MainWindow", "show SubD surface", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A04.setText(QtGui.QApplication.translate("MainWindow", "Reverse Swap", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A05.setText(QtGui.QApplication.translate("MainWindow", "Reverse Both", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_page2_A02.setText(QtGui.QApplication.translate("MainWindow", "show Select Curve CV", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_page2_A06.setText(QtGui.QApplication.translate("MainWindow", "Reverse  Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Shave Tools", None, QtGui.QApplication.UnicodeUTF8))

